config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  'mission',     to: 'static_pages#mission'
  get  'timeline', to: 'static_pages#timeline'
  get  'team', to: 'static_pages#team'
  get  'contacts', to: 'contacts#new'
  resources "contacts", only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Boston Roots Contact",
      :to => "contact@bosroots.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name,     presence: true
  validates :bio,      presence: true
  validates :position, presence: true

  validates_uniqueness_of :name, :scope => :position
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    if (@contact.valid?)
      @contact.request = request
      if @contact.deliver
        flash[:notice] = 'Thank you for your message. We will contact you soon!'
        redirect_to contacts_path
      else
        flash[:error] = 'Cannot send message.'
        render :new
      end
    else
      flash.clear
      render :new
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def team
    @teamMembers = Member.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    def embedded_svg filename, options={}
        file = File.read(Rails.root.join('app', 'assets', 'images', filename))
        doc = Nokogiri::HTML::DocumentFragment.parse file
        svg = doc.at_css 'svg'
        if options[:class].present?
         svg['class'] = options[:class]
        end
        doc.to_html.html_safe
    end
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/contacts/new.html.haml
%section#contact
  #contactheader.header
    %h1 Get Involved
  #contactbody.notebook
    .subheader
      %p 
        Interested in being part of the Boston Roots team?
      %p
        Join as a mentor or start a chapter at your university! Tell us who you are and why you’re interested and we will reach out to you shortly. 
    = simple_form_for @contact, defaults: {label: false} do |f|

      - if @contact.errors.any?
        .error_message
          = evil_icon 'ei-exclamation', size: :m
          %h4 
            Oops...
          %ul.errors
            - @contact.errors.full_messages.each do |msg|
              %li= msg

      - if flash[:notice]
        = evil_icon 'ei-check', size: :l
        .notice
          = flash[:notice] 

      - if flash[:error] && !(@contact.errors.any?)
        = evil_icon 'ei-exclamation', size: :l
        .notice
          = flash[:error] 

      = f.input :name,  :required => false, placeholder: 'Name', :autofocus => true
      = f.input :email, :required => false, placeholder: 'Email'
      = f.input :message, :as => :text, :required => false, placeholder: 'Message'
      .hidden
        = f.input :nickname, :hint => 'Leave this field blank!'
      = f.button :submit, 'Send', class: 'btn btn-join', id: "contactSubmit"

app/views/layouts/application.html.haml
%html
  %head
    %title Boston Roots
    = csrf_meta_tags

    %meta{ charset:"utf-8"}
    %meta{ "http-equiv" => "x-ua-compatible", content: "ie=edge"}
    %meta{ name:"viewport", content:"width=device-width, initial-scale=1" }
    %meta{name:"google-site-verification", content: "I9wqLKpcv-2sIKmUvOd8TVg2dQoffTNLqW17B0jOu2E"}

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = favicon_link_tag       'favicon.png', type: 'image/png'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = evil_icons_sprite

  %body{"data-spy" => "scroll", "data-target" => ".navbar", "data-offset" => "50"}
    #site_wrapper
      %nav.navbar.navbar-fixed-top.short-shadow
        #navlinks
          .navtable
            %ul#left-subnav.nav.navbar-nav.nav-pills
              %li.nav-option.nav-on-only{onclick: "return toggleMobileNav();"}
                = evil_icon 'ei-close', size: :m 
              %li.nav-option.nav-on-only
                = link_to "Home", root_path
              %li.nav-option
                = link_to "Mission", mission_path
              %li.nav-option
                = link_to "Timeline", timeline_path
            %ul.navbar-brand#nav_brand.nav.navbar-nav.nav-pills
              %li
                = link_to image_tag("favicon.png"), root_path, {onclick: "return toggleMobileNav();"}
            %ul#right-subnav.nav.navbar-nav.nav-pills
              %li.nav-option
                = link_to "Team", team_path
              %li.nav-option
                = link_to "Join us", contacts_path
              
      .major_wrapper
        = yield

    %section#footer
      .notebook
        %p © Copyright 2017 Boston Roots, All Rights Reserved

app/views/static_pages/home.html.haml
%section#home
  .background
    .jumbotron.foreground
      #jumboimagecontainer
        #jumboimage
          =image_tag "bostonroots_logo_orange.png"
      #jumbotext
        %h1 
          We are 
          %span{style: "font-weight: bold"} Boston Roots,
          a Nonprofit College Access Initiative.
        #jumboarrow
          = evil_icon 'ei-arrow-down', size: :l, class: "home-icon"

%section#facts
  .notebook
    .fact
      %p
        Because higher education is a
        %b right.
    / .fact
    /   %h2
    /     38 mins
    /   #clock
    /     = embedded_svg "clock_icon.svg"
    /   %p 
    /     Minutes the average student receives from their public school guidance department cross 4 years.
    / .fact 
    /   %h2
    /     472 to 1
    /   #people
    /   - 0.upto(200) do |_|
    /     #person
    /       = embedded_svg "person.svg"
#premission
%section#mission_lite
  .background
    .filter#missionfilter.foreground
      #missionheader.header
        %h1 Mission
      #missionbody.notebook
        .card#missioncard
          #missioncardbody
            %h2 Mission Statement
            %p
              Boston Roots is a nonprofit organization that seeks to shrink the opportunity gap in our country by empowering students to succeed throughout high school and the college admissions process.
          %p#missioncardfooter
            = link_to "Learn more...", mission_path
        .card
          %h2 Student Guidance
          %p Lack of access to college counseling services, financial information, and SAT/ACT prep courses can be major setbacks to students applying to college. Boston Roots provides guidance and college prep services at no cost to high school students and their families. Every high schooler in our program is put in touch with a trained university student mentor who regularly meets and interacts with them throughout their high school years.
        .card
          %h2 Fostering Connections
          %p Boston Roots firmly believes that parent involvement contributes to a higher degree of student success. As a result, our program works with parents to give their children greater support through parent seminars. Topics include student progress, financial saving information, and support strategies to motivate students. Moreover, we intend to connect students with third party SAT/ACT tutors and financial experts for extra support when it is needed.
      .notebook
        = link_to "JOIN US", contacts_path, :class => "button btn btn-join", :id => "bigjoin"

app/views/static_pages/mission.html.haml
%section#mission.first_section
    .header
        .header_text
            %h1 Mission
            #mission_intro
                %p
                    Boston Roots is a nonprofit organization that seeks to shrink the opportunity gap in our country by empowering students to succeed throughout high school and the college admissions process.
    .notebook
        #mission_body
            #para1
                .subheader
                    %h2 The Problem
                .tab_schools
                    .col#private_schools
                        .col_header Private School
                        .col_body
                            The environment is specifically catered to students from Day 1. College counselors strive to work with their students from Freshmen year to meet their individual academic goals. Private school students are usually better prepared when it comes to the application phase because their counselors guide them through every phase.
                    .col#public_schools
                        .col_header Public School
                        .col_body
                            The environment is a “one size fits all.” Most public school students rarely work with their school counselors before the latter half of junior year or beginning of senior year. Counselors focus on getting students into a college rather than actually finding the right fit for their students because of the sheer number of students they have to work with.

                .conclusion
                    %p
                        Public school students are usually less prepared for the application phase because they have fewer resources to rely on.
            .sep
            #para2
                .subheader
                    %h2
                        Our Solution:
                        %span{style: "font-weight: bold"}
                            Boston Roots Mentorship Program
                %p
                    The Boston Roots mentorship program is designed to partner our students with an experienced mentor who can guide them throughout their remaining two years in high school. They provide students with the tools they need to succeed with the college application phase. It’s important to remember that our mentors were once students going through the exact same process, which is why they are in a perfect position to guide others facing the same task. As our students learn from our mentors, they collect priceless information not only on the college app but also what it takes to succeed in a university atmosphere.
            .sep
            #para3
                .subheader
                    %h2 How?
                %p Our mentors will:
                .conclusion
                    %ol
                        %li	Help students develop their extracurricular interests.
                        %li	Build an impressive college profile for applications.
                        %li	Advise students on their academic goals.
                        %li	Guide students throughout the college application.
                %p
                    Interested in participating? Contact us now and
                    = link_to "join us.", contacts_path

app/views/static_pages/team.html.haml
%section#team.first_section
  #teamheader.header
    .header_text
      %h1 Team
      %p 
        We are Boston Roots,
        a Nonprofit College Access Initiative.
        Get to know us!
  #teambody.notebook
    .profile_table_container
      .profile_table
        - @teamMembers.each_slice(2) do |slice|
          - slice.each_with_index do |member, index|
            .profile{class: "side#{index}"}
              .profile_header.long-shadow
                .profile_image
                  - if member.path.blank?
                    = image_tag "profiles/default_profile.jpg"
                  - else
                    = image_tag "profiles/#{member.path}"
                .profile_card
                  .profile_name
                    = evil_icon 'ei-chevron-down', size: :m, class: "left_chevron"
                    %h2
                      = member.name 
                    = evil_icon 'ei-chevron-down', size: :m, class: "right_chevron"
                  .profile_pos
                    %h5
                      = member.position
              %input{type: "radio", name: "teambio"}
              .profile_bio.long-shadow
                %p
                  = member.bio

app/views/static_pages/timeline.html.haml
%section#timeline.first_section
  .header
    .header_text
      %h1
        Timeline
      %p
        This is our track so far.
  %ul.timeline
    %li.timeline-date
      %h4 2015
    %li.timeline-component
      .timeline-badge
        %a
          %p
            &#x25CF;
      .timeline-panel.card
        .timeline-heading
          %h4 Idea Formed
    %li.timeline-component.timeline-inverted
      .timeline-badge
        %a
          %p
            &#x25CF;
      .timeline-panel.card
        .timeline-heading
          %h4 Team Gathered
    %li.timeline-component
      .timeline-badge
        %a
          %p
            &#x25CF;
      .timeline-panel.card
        .timeline-heading
          %h4 Non-profit status acquired
    %li.timeline-date
      %h4 2016
    %li.timeline-inverted.timeline-component
      .timeline-badge
        %a
          %p
            &#x25CF;
      .timeline-panel.card
        .timeline-heading
          %h4 Highschool student outreach

    %li.timeline-component
      .timeline-badge
        %a
          %p
            &#x25CF;
      .timeline-panel.card
        .timeline-heading
          %h4 Mentor Recruitement

    %li.timeline-inverted.timeline-component
      .timeline-badge
        %a
          %p
            &#x25CF;
      .timeline-panel.card
        .timeline-heading
          %h4 Pilot Program Launch

    %li.clearfix.no-float
    %li.timeline-date
      %h4 2017